import type { NextPage } from "next";
import Head from "next/head";
import Dashboard from "./dashboard/index";
import axios from "axios";
import { GetStaticProps, GetServerSideProps } from "next";
import { UserProps, Welcome } from "../types";

const Home: NextPage<{ users: Welcome[] }> = ({ users }) => {
  return (
    <div>
      <Head>
        <title> Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard users={users} />
    </div>
  );
};

export const getStaticProps: GetStaticProps<UserProps> = async () => {
  const res = await axios.get(
    "https://mocki.io/v1/bb11aecd-ba61-44b9-9e2c-beabc442d818"
  );
  const users: Welcome[] = await res.data;
  return {
    props: { users },
  };
};

export default Home;
